// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfsktwwlkmdieldnqlqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmc2t0d3dsa21kaWVsZG5xbHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDIyNDAsImV4cCI6MjA2MzUxODI0MH0.r29c6oETW5iQYgf-f8wV1ZcQnpS9VeFvX9hWg1XooP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);